### ISSUE TITLE
Question about the final prompt generation

### ISSUE THREAD

**Issue by OYE93** [jiaxiaojunQAQ/I-GCG#2]
Hey @jiaxiaojunQAQ, thanks for the work.

I am trying to understand the whole flow and run the repo to reproduce the work. Could you please help me to understand how the final prompt is generated, I can see there is a `adv_suffix` attribute in the log files, like `| ! uns ! some ! both ! might ! wasn ! didn ! ! ! ! ! ! !` and also the original `user_prompt`, I am thinking the final prompting is something like `user_prompt`+`adv_suffix`?

Another question is about another output folder `submission`, if I understand the code correctly, the `generations` is written to these files, but in `attack_llm_core_xxxx.py` files, I can see it's always set something like `generations[user_prompt] = []`, isn't this always an empty list written?

Thanks in advance for your help.

**Comment by jiaxiaojunQAQ** [comment]
> Hey @jiaxiaojunQAQ, thanks for the work.
> 
> I am trying to understand the whole flow and run the repo to reproduce the work. Could you please help me to understand how the final prompt is generated, I can see there is a `adv_suffix` attribute in the log files, like `| ! uns ! some ! both ! might ! wasn ! didn ! ! ! ! ! ! !` and also the original `user_prompt`, I am thinking the final prompting is something like `user_prompt`+`adv_suffix`?
> 
> Another question is about another output folder `submission`, if I understand the code correctly, the `generations` is written to these files, but in `attack_llm_core_xxxx.py` files, I can see it's always set something like `generations[user_prompt] = []`, isn't this always an empty list written?
> 
> Thanks in advance for your help.

1. Yes, the final jailbreak prompt is the user_prompt+adv_suffix.
2. Sorry, generations[user_prompt] is not used in the code.

**Comment by OYE93** [comment]
Ohhh, I see, thanks for the quick response
